# Generated by Django 5.1.1 on 2024-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
