# Generated by Django 5.1.1 on 2024-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_yaounde_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingspolygons',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='electricitylines',
            options={'ordering': ['location']},
        ),
        migrations.AlterModelOptions(
            name='yaounde',
            options={'ordering': ['division']},
        ),
        migrations.AlterField(
            model_name='buildingspolygons',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buildingspolygons',
            name='osm_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='buildingspolygons',
            name='osm_way_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='electricitylines',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electricitylines',
            name='osm_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
