# Generated by Django 5.1.1 on 2024-10-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_buildingspolygons_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingsPolygons',
        ),
        migrations.DeleteModel(
            name='ElectricityLines',
        ),
        migrations.DeleteModel(
            name='Yaounde',
        ),
    ]
